from __future__ import annotations

import json
from typing import Any, Dict

def export_torchrun(plan: Dict[str, Any], serve_py: str = "serve.py") -> str:
    # Very small, deterministic script generator.
    # You can replace serve.py with your actual server or runner entry point.
    world_size = 0
    for s in plan.get("pipeline_stages", []):
        world_size += len(s.get("placement", []))
    if world_size <= 0:
        world_size = 1

    env_lines = [
        "export NCCL_DEBUG=WARN",
        "export CUDA_DEVICE_MAX_CONNECTIONS=1",
    ]

    cmd = [
        "torchrun",
        f"--nproc_per_node={world_size}",
        serve_py,
        "--plan",
        "plan.json",
    ]

    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "# Auto-generated by axm-zombie-adapter",
        *env_lines,
        "",
        "echo "Launching torchrun with plan.json"",
        " ".join(cmd),
        "",
    ]
    return "\n".join(lines)
