from __future__ import annotations
from pathlib import Path
from typing import Any, Dict, List
import json

BASE_PORT = 50052

def _ordered_devices(plan: Dict[str, Any]) -> List[Dict[str, Any]]:
    records = {(g["node"], g["gpu"]): g for g in plan["cluster"]["gpus"]}
    devices: List[Dict[str, Any]] = []
    for st in plan["pipeline_stages"]:
        for p in st["placement"]:
            g = records[(p["node"], p["gpu"])]
            devices.append({
                "node": g["node"],
                "gpu": int(g["gpu"]),
                "host": g.get("host") or f"<{g['node']}-address>",
                "vram_gb": float(g["vram_gb"]),
                "port": BASE_PORT + int(g["gpu"]),
            })
    return devices

def _fmt_num(x: float) -> str:
    return f"{x:g}"

def export_llamacpp(plan: Dict[str, Any], outdir: Path) -> None:
    (outdir / "plan.json").write_text(json.dumps(plan, indent=2), encoding="utf-8")

    devices = _ordered_devices(plan)
    rpc_list = ",".join(f"{d['host']}:{d['port']}" for d in devices)
    tensor_split = ",".join(_fmt_num(d["vram_gb"]) for d in devices)

    by_node: Dict[str, List[Dict[str, Any]]] = {}
    for d in devices:
        by_node.setdefault(d["node"], []).append(d)

    lines = []
    lines.append("# llama.cpp RPC placement notes")
    lines.append("")
    lines.append("llama.cpp repo: https://github.com/ggml-org/llama.cpp")
    lines.append("")
    lines.append("This exporter writes scaffolds and placement notes only. Build llama.cpp")
    lines.append("with the RPC backend (GGML_RPC=ON) plus your device backend (CUDA, Vulkan,")
    lines.append("ROCm, Metal) on each node, and provide your model as a .gguf file.")
    lines.append("")
    lines.append(f"Model: {plan['model']['name']} ({plan['model']['dtype']})")
    lines.append(f"Stages: {len(plan['pipeline_stages'])}")
    lines.append(f"Target TPS: {plan['policy'].get('target_tps')}")
    lines.append("")
    lines.append("## Device order (pipeline order)")
    for d in devices:
        lines.append(f"- {d['node']}:gpu:{d['gpu']} -> {d['host']}:{d['port']} ({_fmt_num(d['vram_gb'])} GB)")
    lines.append("")
    lines.append("## How the scaffolds fit together")
    lines.append("")
    lines.append("1. On each worker node: `./run_rpc_workers.sh <node-id>` starts one")
    lines.append("   rpc-server per GPU on that node.")
    lines.append("2. On the host: `MODEL=/path/to/model.gguf ./run_llamacpp_host.sh` starts")
    lines.append("   llama-server with `--rpc` pointing at every worker in pipeline order")
    lines.append("   and `--tensor-split` proportional to each device's VRAM.")
    lines.append("")
    lines.append("Notes:")
    lines.append("- Device pinning uses CUDA_VISIBLE_DEVICES in the scaffold. On Vulkan use")
    lines.append("  GGML_VK_VISIBLE_DEVICES; on ROCm use HIP_VISIBLE_DEVICES. The plan is")
    lines.append("  vendor-neutral; the pinning variable is the only thing to change.")
    lines.append("- Flag names match llama.cpp as of 2025; check `rpc-server --help` and")
    lines.append("  `llama-server --help` against your build.")
    lines.append("- The RPC backend is unauthenticated: keep it on a trusted LAN or tunnel.")
    lines.append("- If the host machine also holds GPUs, you can serve its share locally")
    lines.append("  instead of via RPC; drop those entries from --rpc and keep the split.")
    lines.append("")
    (outdir / "llamacpp_notes.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    w = []
    w.append("#!/usr/bin/env bash")
    w.append("set -euo pipefail")
    w.append("")
    w.append("# Auto-generated by axm-zombie-adapter. One rpc-server per local GPU.")
    w.append('NODE="${1:?usage: run_rpc_workers.sh <node-id>}"')
    w.append("")
    w.append('case "$NODE" in')
    for node_id in sorted(by_node):
        w.append(f"  {node_id})")
        for d in by_node[node_id]:
            w.append(
                f"    CUDA_VISIBLE_DEVICES={d['gpu']} rpc-server --host 0.0.0.0 --port {d['port']} &"
            )
        w.append("    wait")
        w.append("    ;;")
    w.append("  *)")
    w.append('    echo "unknown node id: $NODE" >&2')
    w.append("    exit 1")
    w.append("    ;;")
    w.append("esac")
    w.append("")
    p = outdir / "run_rpc_workers.sh"
    p.write_text("\n".join(w), encoding="utf-8")
    p.chmod(0o755)

    h = []
    h.append("#!/usr/bin/env bash")
    h.append("set -euo pipefail")
    h.append("")
    h.append("# Auto-generated by axm-zombie-adapter. Start workers first (run_rpc_workers.sh).")
    h.append('MODEL="${MODEL:?set MODEL to your .gguf path}"')
    h.append("")
    h.append("llama-server \\")
    h.append('  -m "$MODEL" \\')
    h.append("  -ngl 99 \\")
    h.append(f"  --rpc {rpc_list} \\")
    h.append(f"  --tensor-split {tensor_split}")
    h.append("")
    p = outdir / "run_llamacpp_host.sh"
    p.write_text("\n".join(h), encoding="utf-8")
    p.chmod(0o755)
