from __future__ import annotations
from pathlib import Path
from typing import Any, Dict
import json

def export_torchrun(plan: Dict[str, Any], outdir: Path, serve_py: str = "serve.py") -> None:
    (outdir / "plan.json").write_text(json.dumps(plan, indent=2), encoding="utf-8")

    world_size = 0
    for s in plan.get("pipeline_stages", []):
        world_size += len(s.get("placement", []))
    if world_size <= 0:
        world_size = 1

    cmd = [
        "torchrun",
        f"--nproc_per_node={world_size}",
        serve_py,
        "--plan",
        "plan.json",
    ]

    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "# Auto-generated by axm-zombie-adapter",
        "# Replace serve.py with your actual server or runner entry point.",
        "export NCCL_DEBUG=WARN",
        "export CUDA_DEVICE_MAX_CONNECTIONS=1",
        "",
        'echo "Launching torchrun with plan.json"',
        " ".join(cmd),
        "",
    ]
    p = outdir / "run_torchrun.sh"
    p.write_text("\n".join(lines), encoding="utf-8")
    p.chmod(0o755)
